"""empty message

Revision ID: 50510bac0cf4
Revises: 
Create Date: 2023-11-22 22:44:06.532071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50510bac0cf4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_slot', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=mysql.DATETIME(),
               type_=sa.Time(),
               existing_nullable=True)
        batch_op.alter_column('end_time',
               existing_type=mysql.DATETIME(),
               type_=sa.Time(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_slot', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=sa.Time(),
               type_=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.Time(),
               type_=mysql.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
